/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWeddingPlannersRouteImport } from './routes/_authenticated/wedding-planners'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPacotesRouteImport } from './routes/_authenticated/pacotes'
import { Route as AuthenticatedMeuPerfilRouteImport } from './routes/_authenticated/meu-perfil'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedEventosRouteImport } from './routes/_authenticated/eventos'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedFotografosIndexRouteImport } from './routes/_authenticated/fotografos/index'
import { Route as AuthenticatedFotografosIdRouteImport } from './routes/_authenticated/fotografos/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWeddingPlannersRoute =
  AuthenticatedWeddingPlannersRouteImport.update({
    id: '/wedding-planners',
    path: '/wedding-planners',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPacotesRoute = AuthenticatedPacotesRouteImport.update({
  id: '/pacotes',
  path: '/pacotes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeuPerfilRoute = AuthenticatedMeuPerfilRouteImport.update({
  id: '/meu-perfil',
  path: '/meu-perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEventosRoute = AuthenticatedEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFotografosIndexRoute =
  AuthenticatedFotografosIndexRouteImport.update({
    id: '/fotografos/',
    path: '/fotografos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFotografosIdRoute =
  AuthenticatedFotografosIdRouteImport.update({
    id: '/fotografos/$id',
    path: '/fotografos/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/eventos': typeof AuthenticatedEventosRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/pacotes': typeof AuthenticatedPacotesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wedding-planners': typeof AuthenticatedWeddingPlannersRoute
  '/fotografos/$id': typeof AuthenticatedFotografosIdRoute
  '/fotografos/': typeof AuthenticatedFotografosIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/eventos': typeof AuthenticatedEventosRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/pacotes': typeof AuthenticatedPacotesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wedding-planners': typeof AuthenticatedWeddingPlannersRoute
  '/': typeof AuthenticatedIndexRoute
  '/fotografos/$id': typeof AuthenticatedFotografosIdRoute
  '/fotografos': typeof AuthenticatedFotografosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/eventos': typeof AuthenticatedEventosRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/_authenticated/pacotes': typeof AuthenticatedPacotesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/wedding-planners': typeof AuthenticatedWeddingPlannersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/fotografos/$id': typeof AuthenticatedFotografosIdRoute
  '/_authenticated/fotografos/': typeof AuthenticatedFotografosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/calendario'
    | '/eventos'
    | '/financeiro'
    | '/leads'
    | '/meu-perfil'
    | '/pacotes'
    | '/settings'
    | '/wedding-planners'
    | '/fotografos/$id'
    | '/fotografos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/calendario'
    | '/eventos'
    | '/financeiro'
    | '/leads'
    | '/meu-perfil'
    | '/pacotes'
    | '/settings'
    | '/wedding-planners'
    | '/'
    | '/fotografos/$id'
    | '/fotografos'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/calendario'
    | '/_authenticated/eventos'
    | '/_authenticated/financeiro'
    | '/_authenticated/leads'
    | '/_authenticated/meu-perfil'
    | '/_authenticated/pacotes'
    | '/_authenticated/settings'
    | '/_authenticated/wedding-planners'
    | '/_authenticated/'
    | '/_authenticated/fotografos/$id'
    | '/_authenticated/fotografos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/wedding-planners': {
      id: '/_authenticated/wedding-planners'
      path: '/wedding-planners'
      fullPath: '/wedding-planners'
      preLoaderRoute: typeof AuthenticatedWeddingPlannersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pacotes': {
      id: '/_authenticated/pacotes'
      path: '/pacotes'
      fullPath: '/pacotes'
      preLoaderRoute: typeof AuthenticatedPacotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meu-perfil': {
      id: '/_authenticated/meu-perfil'
      path: '/meu-perfil'
      fullPath: '/meu-perfil'
      preLoaderRoute: typeof AuthenticatedMeuPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eventos': {
      id: '/_authenticated/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof AuthenticatedEventosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fotografos/': {
      id: '/_authenticated/fotografos/'
      path: '/fotografos'
      fullPath: '/fotografos/'
      preLoaderRoute: typeof AuthenticatedFotografosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fotografos/$id': {
      id: '/_authenticated/fotografos/$id'
      path: '/fotografos/$id'
      fullPath: '/fotografos/$id'
      preLoaderRoute: typeof AuthenticatedFotografosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedEventosRoute: typeof AuthenticatedEventosRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedMeuPerfilRoute: typeof AuthenticatedMeuPerfilRoute
  AuthenticatedPacotesRoute: typeof AuthenticatedPacotesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWeddingPlannersRoute: typeof AuthenticatedWeddingPlannersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedFotografosIdRoute: typeof AuthenticatedFotografosIdRoute
  AuthenticatedFotografosIndexRoute: typeof AuthenticatedFotografosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedEventosRoute: AuthenticatedEventosRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedMeuPerfilRoute: AuthenticatedMeuPerfilRoute,
  AuthenticatedPacotesRoute: AuthenticatedPacotesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWeddingPlannersRoute: AuthenticatedWeddingPlannersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedFotografosIdRoute: AuthenticatedFotografosIdRoute,
  AuthenticatedFotografosIndexRoute: AuthenticatedFotografosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
