/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWeddingPlannersRouteImport } from './routes/_authenticated/wedding-planners'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPacotesRouteImport } from './routes/_authenticated/pacotes'
import { Route as AuthenticatedMeuPerfilRouteImport } from './routes/_authenticated/meu-perfil'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedFotografosIndexRouteImport } from './routes/_authenticated/fotografos/index'
import { Route as AuthenticatedEventosIndexRouteImport } from './routes/_authenticated/eventos.index'
import { Route as AuthenticatedFotografosIdRouteImport } from './routes/_authenticated/fotografos/$id'
import { Route as AuthenticatedEventosIdRouteImport } from './routes/_authenticated/eventos.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWeddingPlannersRoute =
  AuthenticatedWeddingPlannersRouteImport.update({
    id: '/wedding-planners',
    path: '/wedding-planners',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPacotesRoute = AuthenticatedPacotesRouteImport.update({
  id: '/pacotes',
  path: '/pacotes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeuPerfilRoute = AuthenticatedMeuPerfilRouteImport.update({
  id: '/meu-perfil',
  path: '/meu-perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedFotografosIndexRoute =
  AuthenticatedFotografosIndexRouteImport.update({
    id: '/fotografos/',
    path: '/fotografos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEventosIndexRoute =
  AuthenticatedEventosIndexRouteImport.update({
    id: '/eventos/',
    path: '/eventos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFotografosIdRoute =
  AuthenticatedFotografosIdRouteImport.update({
    id: '/fotografos/$id',
    path: '/fotografos/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEventosIdRoute = AuthenticatedEventosIdRouteImport.update({
  id: '/eventos/$id',
  path: '/eventos/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/pacotes': typeof AuthenticatedPacotesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wedding-planners': typeof AuthenticatedWeddingPlannersRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/eventos/$id': typeof AuthenticatedEventosIdRoute
  '/fotografos/$id': typeof AuthenticatedFotografosIdRoute
  '/eventos/': typeof AuthenticatedEventosIndexRoute
  '/fotografos/': typeof AuthenticatedFotografosIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/pacotes': typeof AuthenticatedPacotesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wedding-planners': typeof AuthenticatedWeddingPlannersRoute
  '/': typeof AuthenticatedIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/eventos/$id': typeof AuthenticatedEventosIdRoute
  '/fotografos/$id': typeof AuthenticatedFotografosIdRoute
  '/eventos': typeof AuthenticatedEventosIndexRoute
  '/fotografos': typeof AuthenticatedFotografosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/_authenticated/pacotes': typeof AuthenticatedPacotesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/wedding-planners': typeof AuthenticatedWeddingPlannersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/eventos/$id': typeof AuthenticatedEventosIdRoute
  '/_authenticated/fotografos/$id': typeof AuthenticatedFotografosIdRoute
  '/_authenticated/eventos/': typeof AuthenticatedEventosIndexRoute
  '/_authenticated/fotografos/': typeof AuthenticatedFotografosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/calendario'
    | '/financeiro'
    | '/leads'
    | '/meu-perfil'
    | '/pacotes'
    | '/settings'
    | '/wedding-planners'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/eventos/$id'
    | '/fotografos/$id'
    | '/eventos/'
    | '/fotografos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/calendario'
    | '/financeiro'
    | '/leads'
    | '/meu-perfil'
    | '/pacotes'
    | '/settings'
    | '/wedding-planners'
    | '/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/eventos/$id'
    | '/fotografos/$id'
    | '/eventos'
    | '/fotografos'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/calendario'
    | '/_authenticated/financeiro'
    | '/_authenticated/leads'
    | '/_authenticated/meu-perfil'
    | '/_authenticated/pacotes'
    | '/_authenticated/settings'
    | '/_authenticated/wedding-planners'
    | '/_authenticated/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/eventos/$id'
    | '/_authenticated/fotografos/$id'
    | '/_authenticated/eventos/'
    | '/_authenticated/fotografos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/wedding-planners': {
      id: '/_authenticated/wedding-planners'
      path: '/wedding-planners'
      fullPath: '/wedding-planners'
      preLoaderRoute: typeof AuthenticatedWeddingPlannersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pacotes': {
      id: '/_authenticated/pacotes'
      path: '/pacotes'
      fullPath: '/pacotes'
      preLoaderRoute: typeof AuthenticatedPacotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meu-perfil': {
      id: '/_authenticated/meu-perfil'
      path: '/meu-perfil'
      fullPath: '/meu-perfil'
      preLoaderRoute: typeof AuthenticatedMeuPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/fotografos/': {
      id: '/_authenticated/fotografos/'
      path: '/fotografos'
      fullPath: '/fotografos/'
      preLoaderRoute: typeof AuthenticatedFotografosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eventos/': {
      id: '/_authenticated/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof AuthenticatedEventosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fotografos/$id': {
      id: '/_authenticated/fotografos/$id'
      path: '/fotografos/$id'
      fullPath: '/fotografos/$id'
      preLoaderRoute: typeof AuthenticatedFotografosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eventos/$id': {
      id: '/_authenticated/eventos/$id'
      path: '/eventos/$id'
      fullPath: '/eventos/$id'
      preLoaderRoute: typeof AuthenticatedEventosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedMeuPerfilRoute: typeof AuthenticatedMeuPerfilRoute
  AuthenticatedPacotesRoute: typeof AuthenticatedPacotesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWeddingPlannersRoute: typeof AuthenticatedWeddingPlannersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedEventosIdRoute: typeof AuthenticatedEventosIdRoute
  AuthenticatedFotografosIdRoute: typeof AuthenticatedFotografosIdRoute
  AuthenticatedEventosIndexRoute: typeof AuthenticatedEventosIndexRoute
  AuthenticatedFotografosIndexRoute: typeof AuthenticatedFotografosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedMeuPerfilRoute: AuthenticatedMeuPerfilRoute,
  AuthenticatedPacotesRoute: AuthenticatedPacotesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWeddingPlannersRoute: AuthenticatedWeddingPlannersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedEventosIdRoute: AuthenticatedEventosIdRoute,
  AuthenticatedFotografosIdRoute: AuthenticatedFotografosIdRoute,
  AuthenticatedEventosIndexRoute: AuthenticatedEventosIndexRoute,
  AuthenticatedFotografosIndexRoute: AuthenticatedFotografosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
